---
# tasks file for sysstat

- block:
    - name: install sysstat
      become: yes
      become_method: sudo
      apt:
        name: sysstat
        cache_valid_time: "{{ apt_cache_valid_time|default(omit) }}"
        install_recommends: no
        state: latest
        update_cache: yes

    - name: copy sysstat default configuration
      template:
        src: default_sysstat.j2
        dest: /etc/default/sysstat
        backup: no
        mode: "0644"
      notify:
        - reload sysstat

    - name: ensure sysstat service running and enabled on boot
      service:
        name: "{{ sysstat_service_name }}"
        enabled: yes
        state: started

  become: yes
  become_method: sudo
  tags:
    - sysstat
    - common
